version = 0.1
[default.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TimestreamDatabaseName=\"prediction_markets_temp\" TimestreamTableName=\"predictittemp\" TimestreamCompositePartitionKey=\"Contract_ID\""
image_repositories = []
